twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    # globals:
    #     hcaptcha_site_key: '%env(HCAPTCHA_SITEKEY)%'

    # globals:
    #     gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

when@test:
    twig:
        strict_variables: true
