twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [
        'bootstrap_5_layout.html.twig',
        '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        ]
        
    # globals:
    #     recherche: '@App\Generator\UuidGenerator'

    # globals:
    #     uuid: '@App\Generator\UuidGenerator'

    # globals:
    #     gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

when@test:
    twig:
        strict_variables: true
